security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Définir un firewall spécifique pour /films/loading sans authentification
        films_loading:
            pattern: ^/films
            security: false

        # Le firewall principal pour les autres routes
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_accueil
                enable_csrf: true
            logout:
                path: app_logout
                target: app_accueil
            entry_point: form_login

    access_control:
        - { path: ^/administrateur, roles: ROLE_ADMIN }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/utilisateur, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
