vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        image_film:
            uri_prefix: /image_film
            upload_destination: '%kernel.project_dir%/public/image_film'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
